name: gigaturnip
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.7+45

environment:
  sdk: ">=3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.4
  firebase_auth: ^4.6.3
  flutter_image_compress: ^2.0.3
  google_sign_in: ^6.0.1
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  json_annotation: ^4.5.0
  authentication_repository:
    path: packages/authentication_repository
  gigaturnip_repository:
    path: packages/gigaturnip_repository
  gigaturnip_api:
    path: packages/gigaturnip_api
  flutter_json_schema_form:
#    path: ../flutter-jsonschema-form
    git:
      url: https://github.com/KloopMedia/flutter-jsonschema-form.git
      ref: master
  font_awesome_flutter: ^10.1.0
  intl: ^0.17.0
  shared_preferences: ^2.0.18
  flutter_launcher_icons: ^0.13.1
  go_router: ^9.0.0
  permission_handler: ^10.2.0
  webview_flutter: ^4.0.5
  rxdart: ^0.27.7
  sliver_tools: ^0.2.9
  universal_html: ^2.2.1
  flutter_downloader: ^1.10.2
  path_provider: ^2.0.14
  dio: ^5.1.1
  pinput: ^2.2.31
  country_code_picker: ^3.0.0
  material_color_utilities: ^0.2.0
  google_fonts: ^5.1.0
  path_drawing: ^1.0.1
  drift: ^2.9.0
  url_launcher: ^6.1.11
  back_button_interceptor: ^6.0.2

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  test: ^1.21.1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/google_icon.png
    - assets/icon/apple_icon.png
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Inter
     fonts:
       - asset: assets/fonts/Inter-Thin.ttf
         weight: 100
       - asset: assets/fonts/Inter-ExtraLight.ttf
         weight: 200
       - asset: assets/fonts/Inter-Light.ttf
         weight: 300
       - asset: assets/fonts/Inter-Medium.ttf
         weight: 500
       - asset: assets/fonts/Inter-Regular.ttf
         weight: 400
       - asset: assets/fonts/Inter-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/Inter-Bold.ttf
         weight: 700
       - asset: assets/fonts/Inter-ExtraBold.ttf
         weight: 800
       - asset: assets/fonts/Inter-Black.ttf
         weight: 900

#     - family: Schyler
#       fonts:
#         - asset: fonts/Schyler-Regular.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
